# Site settings
title: The Peace Corps ICT4D Playbook
short_title: ICT4D Playbook
description: |
    Volunteers using information and communication technologies for development.
baseurl: http://playbook.peacecorpsict4d.org
github_username:  peacecorps
github_repo:  ict4d-playbook

# contributors:
#   -
#       name: 
#       link: 

googleanalytics: UA-73371163-1

markdown: kramdown

kramdown:
  parse_block_html: true

permalink: pretty

gems:
  - jemoji

meta:
  guide:
    toc:
      chapters:
        - title: 'Introduction'
          slug: 'introduction'
        - title: 'Why ICT4D?'
          slug: 'why-ict4d'
        - title: 'What is ICT4D?'
          slug: 'what-is-ict4d'
        - title: 'Strategy'
          slug: 'strategy'
        - title: 'Principles'
          slug: 'principles'
        - title: 'Initiatives'
          slug: 'initiatives'
        - title: 'ICT4D for Volunteers'
          slug: 'ict4d-for-volunteers'
        - title: 'ICT4D for Staff'
          slug: 'ict4d-for-staff'
        # - title: 'FAQ'
        #   slug: 'faq'
        # - title: 'History'
        #   slug: 'history'
        # - title: 'Glossary'
        #   slug: 'glossary'
  program-areas:
    toc:
      chapters:
        - title: 'Digital Literacy'
          slug: 'digital-literacy'
        - title: 'ICTs for Education'
          slug: 'icts-for-education'
        - title: 'Technology for Monitoring & Evaluation'
          slug: 'technology-for-monitoring-and-evaluation'
        - title: 'Design Thinking'
          slug: 'design-thinking'
        - title: 'GIS and Mapping'
          slug: 'gis-and-mapping'
        - title: 'Girls and STEM Education'
          slug: 'girls-and-stem-education'
        - title: 'Mobile Communications'
          slug: 'mobile-communications'
        - title: 'Radio and Mass Media'
          slug: 'radio-and-mass-media'
        - title: 'Libraries and Maker Spaces'
          slug: 'libraries-and-maker-spaces'
        - title: 'Climate Change Education'
          slug: 'climate-change-education'
        - title: 'mHealth'
          slug: 'mhealth'
        - title: 'Media Production'
          slug: 'media-production'
        - title: 'Youth Workforce Employment'
          slug: 'youth-workforce-employment'
        - title: 'Tools and Technologies'
          slug: 'tools-and-technologies'
  contribute:
    toc:
      chapters:
        - title: 'Contribute'
          slug: ''
        - title: 'Edit a page'
          slug: 'editing'
        - title: 'Adding a page'
          slug: 'adding'
        - title: 'Markdown examples'
          slug: 'markdown-examples'

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
collections:
  volunteer-projects:
    output: true